// Výkladový slovník. Každý pojem má vzorec, pásma a větu o tom, co s tím dělat.
// Pole `source` drží původ čísel — ať je poznat, co je publikované a co konvence.

export const GLOSSARY_GROUPS = [
  { id: 'zaklad', label: 'Základní pojmy' },
  { id: 'objem', label: 'Objem a intenzita' },
  { id: 'unava', label: 'Únava a zátěž' },
  { id: 'planovani', label: 'Plánování bloku' },
  { id: 'zavod', label: 'Závod a skóre' },
];

export const GLOSSARY = [
  /* ---------------- Základní pojmy ---------------- */
  {
    id: 'e1rm',
    group: 'zaklad',
    term: 'E1RM',
    full: 'Odhadované jednorepetiční maximum',
    short: 'Kolik by závodník dnes zvedl na jeden pokus, spočítané z lehčí série.',
    formula: 'E1RM = váha ÷ (% z 1RM) × 100',
    body: 'Testovat opravdové maximum stojí týden regenerace. Místo toho se maximum dopočítá z běžné pracovní série. Čím blíž je série jednorepetičnímu maximu, tím přesnější odhad — pětka na RPE 8 je spolehlivá, dvanáctka na RPE 6 hádání.',
    how: 'Ber E1RM jako klouzavý ukazatel formy, ne jako číslo do medailí. Když stejná váha na stejné opakování jede na nižší RPE, forma roste — i když jsi nic netestoval.',
    source: 'Vzorce Epley, Brzycki, Lombardi, O\'Conner, Wathan, Mayhew, Landers; RPE varianta podle tabulky RTS. Osmá, váhově závislá varianta: Marzagão (2026), arXiv:2603.17495 — optimalizovaná na 303 494 sérií blízko selhání a jako jediná ví, že 20 kg × 10 a 200 kg × 10 nejsou totéž. Je závislá na jednotkách; abstrakt je neuvádí, ověřil jsem je proti publikovaným kontrolním hodnotám (100 kg × 5 → 117,5 a 40 kg × 10 → 58,0), takže jednotka je kilogram. Preprint, nerecenzovaný, a laděný na vnitřní konzistenci, ne proti změřeným maximům — proto je volitelný, ne výchozí.',
  },
  {
    id: 'plateau',
    group: 'zaklad',
    term: 'Detekce plateau',
    full: 'Je trend E1RM reálný posun, nebo jen šum?',
    short: 'Appka odliší skutečnou stagnaci od běžného kolísání kolem stejné úrovně.',
    formula: 'plateau, pokud |sklon × sledované období| < rozptyl bodů kolem přímky',
    body: 'Přehled ukazuje u každého cviku sklon křivky (kolik kg za měsíc), ale samotné číslo neřekne, jestli je to skutečný trend, nebo jen šum kolem nuly — pár odhadů E1RM se přirozeně liší i bez jakékoli změny formy. Appka proto porovná, o kolik se proložená přímka za celé sledované období posunula, s tím, jak moc se od ní jednotlivé body typicky odchylují. Pohne-li se přímka míň, než je ten běžný rozptyl, nejde o prokazatelný trend.',
    bands: [
      { range: 'Roste / klesá', label: 'Posun přímky je větší než typický rozptyl bodů', tone: 'ok' },
      { range: 'Beze změny', label: 'Posun je menší než šum — nejde o prokazatelný trend', tone: 'warn' },
      { range: 'Málo dat', label: 'Potřeba aspoň 3 zapsaná maxima', tone: 'low' },
    ],
    how: 'Se dvěma body appka nic neřekne — přímka jimi projde přesně a šum vyjde nulový. Čím víc maxim je zapsaných a čím jsou pravidelnější, tím dřív appka pozná skutečnou stagnaci od náhodného výkyvu.',
    source: 'Obecný statistický princip (signál proti šumu reziduí lineární regrese) — appka ho aplikuje na vlastní e1rmLog, nejde o publikovaný vzorec specifický pro powerlifting.',
  },
  {
    id: 'sdc',
    group: 'zaklad',
    term: 'Prokazatelná změna',
    full: 'Typická chyba měření a nejmenší prokazatelná změna (SDC)',
    short: 'O kolik se musí odhad maxima pohnout, aby to nebyl jen dobrý den.',
    formula: 'typická chyba = rozptyl zápisů kolem proložené přímky\nSDC = 1,96 · √2 · typická chyba ≈ 2,77 · typická chyba',
    bands: [
      { range: 'pod SDC', label: 'Změna se vejde do šumu — může to být jen den', tone: 'warn' },
      { range: 'nad SDC', label: 'Posun je s 95% jistotou skutečný', tone: 'ok' },
      { range: 'pod 4 zápisy', label: 'Málo dat, chyba se nedá odhadnout', tone: 'low' },
    ],
    body: 'Odhad maxima kolísá i bez jakékoli změny síly: jinak sedící pás, horší spánek, RPE odhadnuté o půl bodu vedle. Typická chyba je právě tohle kolísání — spočítá se jako rozptyl zápisů kolem proložené přímky, protože přímka drží skutečný trend a to, co od ní zbývá, je šum. Nejmenší prokazatelná změna z ní vychází: 1,96 je 95% kvantil normálního rozdělení a √2 je tam proto, že v rozdílu dvou měření sedí chyba obou.',
    how: 'Praktický dopad je na frekvenci testování: když typická chyba vyjde na 4 kg, potřebuješ posun přes 11 kg, aby se dal obhájit. Testovat maximum každý týden pak nemá co změřit — mezi testy musí uplynout tolik času, kolik zabere zlepšení nad tímhle prahem.',
    source: 'Hopkins (2000, 2004) pro typickou chybu; Weir (2005) pro MDC95. Spodní mez 3 % z průměru je hranice zvolená appkou: dokonale lineární řada zápisů by dala nulový rozptyl a appka by pak prohlásila za prokazatelný i posun o gram. Publikovaná variabilita odhadu 1RM z predikčních rovnic je 4,5 až 13,2 % a v platném rozsahu opakování se odhad od změřeného maxima liší zhruba o ±5 %; k tomu přibývá chyba samotného RPE (Helms a kol. 2017: odchylka nahlášeného od cíleného 0,33 ± 0,28 bodu). Hranice 3 % tedy leží pod spodním okrajem publikovaného rozpětí — appka spíš podstřelí, než aby prohlásila šum za zlepšení.',
  },
  {
    id: 'pomery',
    group: 'zaklad',
    term: 'Rozložení součtu',
    full: 'Podíly dřepu, benčpresu a mrtvého tahu na součtu',
    short: 'Jestli je součet poskládaný jako u elity ve stejné kategorii — nebo jeden cvik zaostává.',
    formula: 'podíl cviku = cvik ÷ součet × 100\npásmo = průměr elity ± f · směrodatná odchylka',
    bands: [
      { range: 'v pásmu', label: 'Podíl odpovídá elitě ve stejné kategorii, pohlaví a výstroji', tone: 'ok' },
      { range: 'pod pásmem', label: 'Cvik nese menší podíl součtu, než je u elity obvyklé', tone: 'warn' },
      { range: 'nad pásmem', label: 'Cvik nese větší podíl — často silná stránka', tone: 'low' },
    ],
    body: 'Bro pravidla typu 3:4:5 ignorují, že se poměry posouvají s kategorií i výstrojí. Nejlehčí muži dávají v klasice do mrtvého tahu skoro 40 % součtu, nejtěžší jen 37 %. Ve vybavené soutěži je to celé jinak, protože dres pomáhá dřepu a benči, ne tahu. Appka proto nepoužívá jedno univerzální číslo, ale tabulku pro konkrétní váhovou kategorii, pohlaví a výstroj — a k ní i směrodatnou odchylku, takže vedle stavu ukáže i to, jak daleko od elitního průměru závodník je.',
    how: 'Ber to jako otázku, ne jako cíl. Součet se nezvedne tím, že se srovná tabulka — zvedne se tím, že se zvedne cvik, u kterého je největší prostor. Někdy je to ten zaostávající, často ale ten, který na přidaný objem odpovídá nejlíp. A pozor na měřítko: podíly dávají dohromady 100 %, takže jeden propadlý cvik nutně vytlačí zbylé dva nad pásmo — neznamená to, že jsou nadprůměrné.',
    source: 'Hernández Ugalde (2023), „Powerlifting Balance Of SBD Disciplines Ratio To Total Score", Int J Strength Cond 3(1), doi 10.47206/ijsc.v3i1.198. Data z OpenPowerlifting, závody IPF 2012–2022, věk 24–39, 128 tisíc startů. POZOR NA VÝKLAD: studie ukazuje souvislost, ne příčinu — závodníci uvnitř pásma mají vyšší IPF GL, ale z toho neplyne, že narovnání poměru součet zvedne.',
  },
  {
    id: 'vekovy-koeficient',
    group: 'zavod',
    term: 'Věkový koeficient',
    full: 'McCulloch / Foster — srovnání výkonu napříč věkem',
    short: 'Násobitel bodů pro masters a dorost. Násobí se body, ne kilogramy.',
    formula: 'upravené body = DOTS (nebo Wilks, IPF GL) × koeficient(věk)',
    bands: [
      { range: '14–22 let', label: 'Fosterovy koeficienty pro dorost, 1,23 dolů k 1,01', tone: 'ok' },
      { range: '23–40 let', label: 'Koeficient 1,000 — bez úpravy', tone: 'ok' },
      { range: '41–90 let', label: 'McCulloch (Glossbrennerova oprava) a USAPL, 1,010 až 2,549', tone: 'ok' },
      { range: 'do 13 a nad 90', label: 'Ve zdroji označené jako odhad a extrapolace', tone: 'warn' },
    ],
    body: 'Bez věkového koeficientu se nedá obsloužit ani masters, ani dorost — a to je v českých soutěžích velká část startovního pole. Pozor na pořadí: koeficient se násobí výslednými body, ne součtem v kilogramech. Je to úprava skóre, ne přepočet výkonu.',
    how: 'Než se podle toho někam nominuješ, ověř si, kterou variantu tabulky federace uznává. Appka počítá variantu OpenPowerlifting; WRPF má pro stejné věky jiná čísla (v 60 letech 1,380 místo 1,340) a nad 80 let tabulku zastropuje. Rozdíl na hraně nominace rozhodne.',
    source: 'OpenPowerlifting, zdrojový soubor mcculloch.rs (MIT): Fosterovy koeficienty pro 14–22, Glossbrennerem opravený McCulloch pro 41–80, USAPL pro 81–90. Nejsou to výsledky výzkumu — je to historicky dohodnutá federační tabulka bez publikované odvozovací rovnice.',
  },
  {
    id: 'trend-interval',
    group: 'zaklad',
    term: 'Interval spolehlivosti trendu',
    full: 'Jak jistý si tím sklonem vůbec můžeme být',
    short: 'Sklon spočítaný z pár zápisů je sám odhad. Interval říká, kde ten skutečný leží.',
    formula: 'směrodatná chyba sklonu = reziduální rozptyl ÷ √Sxx\ninterval = sklon ± t(0,95; n−2) · směrodatná chyba',
    bands: [
      { range: 'interval neobsahuje nulu', label: 'Směr je průkazný — dá se říct, že roste nebo klesá', tone: 'ok' },
      { range: 'interval obsahuje nulu', label: 'Data neumí rozhodnout. Tvrdit směr by bylo víc, než unesou', tone: 'low' },
      { range: 'průkazný, ale malý', label: 'Za čtyři týdny nedá ani nejmenší prokazatelnou změnu', tone: 'warn' },
    ],
    body: 'Appka dřív rozhodovala o stagnaci podle pravidla, které jsem si vymyslel: posunula se přímka víc, než je rozptyl bodů kolem ní? Fungovalo to, ale existuje na to standardní statistika. Interval spolehlivosti sklonu říká, v jakém rozmezí skutečný sklon leží — a jestli mezi ně patří nula. Pás kolem přímky se rozšiřuje směrem od těžiště dat, protože čím dál od průměrného data, tím míň přímka ví.',
    how: 'Za stagnaci se prohlásí jen případ, kdy platí obojí naráz: interval obsahuje nulu A i kdyby byl trend skutečný, za čtyři týdny nedá prokazatelnou změnu. Kdyby stačila první podmínka, appka by za stagnaci označila i pomalý ale vytrvalý růst u někoho s rozházenými zápisy — a tomu se nemá říkat, že se nikam neposouvá.',
    source: 'Standardní statistika nejmenších čtverců. Kritické hodnoty t-rozdělení pro 1–30 stupňů volnosti, nad 30 se používá 1,96.',
  },
  {
    id: 'robustni-trend',
    group: 'zaklad',
    term: 'Robustní trend',
    full: 'Theil–Sen a Mann–Kendall',
    short: 'Odhad trendu, který nerozhodí jeden špatný den.',
    formula: 'Theil–Sen: sklon = medián všech párových sklonů\nMann–Kendall: S = Σ sign(y_j − y_i), Z = (S ∓ 1) ÷ √var(S)',
    bands: [
      { range: 'oba odhady sedí', label: 'Data jsou čistá, obyčejné regresi se dá věřit', tone: 'ok' },
      { range: 'liší se výrazně', label: 'V datech sedí odlehlá hodnota. Věř robustnímu odhadu', tone: 'warn' },
      { range: 'Z nad 1,96', label: 'Monotónní trend je průkazný na hladině 5 %', tone: 'ok' },
    ],
    body: 'Obyčejná regrese se dá vychýlit jediným bodem — nemocí, zkaženým pokusem, špatně odhadnutým RPE. Nejhůř na tom je bod na kraji řady, který má na sklon největší páku; bod přesně uprostřed naopak sklonem nehne vůbec. Theil–Sen bere medián všech párových sklonů, takže odlehlou hodnotu ostatní dvojice přehlasují. Mann–Kendall se neptá na tvar křivky, jen jestli hodnoty spíš rostou, nebo klesají.',
    how: 'Když se obyčejná regrese a Theil–Sen výrazně rozejdou, je to samo o sobě informace: v datech je odlehlá hodnota. Podívej se, který zápis to je, a rozhodni, jestli patří do trendu, nebo byl výjimka.',
    source: 'Standardní neparametrická statistika. Není to sportovní věda, je to matematika — a v silových aplikacích se prakticky nevidí.',
  },
  {
    id: 'cusum',
    group: 'zaklad',
    term: 'Detekce zlomu',
    full: 'CUSUM — kdy přesně se to zlomilo',
    short: 'Detekce plateau řekne, že se progres zastavil. Tohle řekne, ve kterém zápisu.',
    formula: 'C⁺ = max(0, C⁺ + z − k)\nC⁻ = min(0, C⁻ + z + k)\npoplach při C⁺ > h nebo C⁻ < −h',
    bands: [
      { range: 'bez poplachu', label: 'Úroveň se od výchozí neodchýlila', tone: 'ok' },
      { range: 'C⁻ pod prahem', label: 'Propad proti výchozí úrovni — a datum, kdy začal', tone: 'warn' },
      { range: 'C⁺ nad prahem', label: 'Skok nahoru proti výchozí úrovni', tone: 'ok' },
    ],
    body: 'Sčítá se odchylka od referenční úrovně. Dokud se hodnoty drží kolem ní, součet se drží u nuly; jakmile se úroveň posune, začne utíkat jedním směrem a překročení prahu je poplach. Referenční průměr se bere z první poloviny řady, ne z celku — kdyby se počítal ze všeho, přišel by poplach už v rostoucí části jen proto, že leží nad celkovým průměrem.',
    how: 'Detekce zlomu neříká proč, jen kdy. Až budeš mít datum, podívej se, co se v tom týdnu dělo: přibyl objem, přišla nemoc, změnil se plán? Dokonale plochá řada nemá rozptyl, kterým by se dalo dělit — u ní appka nevrátí nic.',
    source: 'Statistické řízení jakosti. Prahy k a h jsou zvyklosti oboru, ne hodnoty odvozené ze silového tréninku.',
  },
  {
    id: 'modely-taperu',
    group: 'planovani',
    term: 'Modely ladění formy',
    full: 'Krokový, lineární a exponenciální taper',
    short: 'Tři tvary, jak sjet objem do závodu. Liší se hlavně tím, co udělají s mrtvým tahem.',
    formula: 'krokový: objem = 50 % po celý poslední týden\nlineární: objem = 1 − 0,5 · (den ÷ délka)\nexponenciální: objem = 0,5 + 0,5 · e^(−den ÷ (délka ÷ 3))',
    bands: [
      { range: 'Krokový, 7 dnů', label: 'Jednorázový škrt. U benče a krátkých vrcholení stačí', tone: 'ok' },
      { range: 'Lineární, 14 dnů', label: 'Rovnoměrný pokles na polovinu', tone: 'ok' },
      { range: 'Exponenciální, 21 dnů', label: 'Rychlý pokles, pak doznívání. Jediný zvedl i mrtvý tah', tone: 'ok' },
    ],
    body: 'Všechny tři končí na zhruba polovině výchozího objemu — v řízeném pokusu skončily obě porovnávané větve na stejné celkové práci, lišil se jen tvar cesty a délka. A právě ten tvar rozhodl: dřep a bench vyšly srovnatelně, ale mrtvý tah u krokového taperu nevzrostl vůbec (+1 %, nevýznamně), zatímco u exponenciálního o 8 %.',
    how: 'Když je slabinou mrtvý tah, ber exponenciální. Na krátké vrcholení nebo samotný bench stačí krokový. A hlavně: ubírá se práce, ne váha na ose — kdo v posledním týdnu sjede i procenta, přijde o formu, ne o únavu.',
    source: 'Grgic a Mikulic (2017) pro praxi šampionů — POZOR, dotazník na deseti lidech, popis a ne důkaz optimality. Rozdíl mezi modely: řízený pokus, Frontiers in Physiology 2021 (PMC8582352), malý vzorek a šest týdnů sledování. Analytické řešení optimálního tvaru z dvousložkového modelu (arXiv:2505.20859) závisí na parametrech, které pro powerlifting neznáme.',
  },
  {
    id: 'casovani-zavodu',
    group: 'zavod',
    term: 'Časování závodního dne',
    full: 'Kdy začít rozcvičku podle pořadí v nominaci',
    short: 'Osa času počítaná pozpátku od prvního pokusu.',
    formula: 'kolo = počet závodníků × minuta na pokus\n1. pokus = start flighty + (pořadí − 1) × minuta\nposlední rozcvička = 1. pokus − 10 × minuta\nzačátek rozcvičky = poslední rozcvička − (sérií − 1) × pauza',
    bands: [
      { range: 'poslední rozcvička', label: 'Zhruba 10 závodníků před vlastním pokusem, pod 90 % otvíráku', tone: 'ok' },
      { range: 'mezi pokusy', label: 'Uplyne celé kolo — na 2. a 3. pokus se rozcvičovat nemusí', tone: 'ok' },
      { range: 'pauza mezi sériemi', label: '6 minut, na závodě se dělí náčiní', tone: 'ok' },
    ],
    body: 'Rozcvičovací žebřík appka uměla vždycky, chyběla mu ale osa času. Poslední série má padnout dost blízko, aby se nevychladlo, a dost daleko, aby se stihlo dojít na plac. Od toho se počítá pozpátku, kolik sérií se stihne a kdy se musí začít.',
    how: 'Na velkých závodech si připočti rezervu — tempo kolísá s nároky a technickými přestávkami. Proto je minuta na pokus k přenastavení: když flighta jede pomalu, zvedni ji na 1,2 a osa se přepočítá.',
    source: 'EliteFTS, PowerliftingTechnique a další trenérské zdroje. Žádná recenzovaná data — jsou to praxí zaběhnuté konstanty, ne měření.',
  },
  {
    id: 'percentily',
    group: 'zavod',
    term: 'Percentily relativní síly',
    full: 'Kde výkon leží proti populaci závodníků',
    short: 'Násobek tělesné váhy proti 90. percentilu z 810 tisíc startů.',
    formula: 'násobek = výkon ÷ tělesná váha',
    bands: [
      { range: 'nad 90. percentilem', label: 'V nejlepší desetině startovního pole', tone: 'ok' },
      { range: 'pod ním', label: 'Appka ukáže, kolik kilogramů do hranice chybí', tone: 'neutral' },
    ],
    body: 'Jiný pohled než DOTS nebo IPF GL: ty normalizují na tělesnou váhu koeficientem, tohle je prostý násobek. Pro laika je srozumitelnější, na srovnání napříč kategoriemi je ale horší — lehký a těžký závodník se násobkem porovnat pořádně nedají.',
    how: 'Ber to jako orientaci, ne jako cíl. Na medaili se jde přes součet a koeficient, ne přes násobek vlastní váhy.',
    source: 'Normativní data z 809 986 startů, J Sci Med Sport (2024), doi 10.1016/j.jsams.2024.06.008. POZOR: z placeného textu se podařilo ověřit jen 90. percentil a jen pro 18–35 let a nad 80 let. Zbytek tabulky appka nedopočítává — interpolovat chybějící percentily a vydávat je za data by byl výmysl.',
  },
  {
    id: 'sablony',
    group: 'planovani',
    term: 'Hotové šablony',
    full: '5/3/1, Texas, vlnové zatížení, denní maxima',
    short: 'Zaběhnuté programy s dopočítanými váhami — a s tím, co o nich víme.',
    formula: '5/3/1: tréninkové maximum = 90 % z 1RM\ntýden 1: 65/75/85 %, týden 2: 70/80/90 %, týden 3: 75/85/95 %, týden 4 deload',
    bands: [
      { range: '5/3/1', label: 'Appka počítá váhy. Trenérská praxe, ne výzkum', tone: 'ok' },
      { range: 'Texas Method', label: 'Jen popis. Pro pokročilé trojbojaře překonané', tone: 'low' },
      { range: 'Vlnové zatížení', label: 'Jen popis. Žádná přímá evidence', tone: 'low' },
      { range: 'Denní maxima', label: 'Jen popis s varováním. Vysoké riziko, pilotní data', tone: 'bad' },
    ],
    body: 'Nejčastější chyba při zavádění 5/3/1: procenta se počítají z tréninkového maxima, tedy z 90 % skutečného maxima — ne ze samotného maxima. Poslední série každého týdne jde na co nejvíc opakování a právě z ní se pozná, jestli maximum sedí: když nedá ani předepsané minimum, snižuje se o desetinu.',
    how: 'Appka počítá váhy jen u 5/3/1. Ostatní tři jsou tu jako popis s tím, co o nich víme a nevíme — ani jedna nemá přímou evidenci a u denních maxim je riziko takové, že by bylo nepoctivé nabízet je jako hotový plán. Šablony plánovač nepřepisují: jsou to kalkulačky vedle něj.',
    source: 'Wendler (2009) pro 5/3/1; Rippetoe a Baker pro Texas; denní maxima mají jen pilotní studii na malém vzorku (PMC6162635). Všechno trenérská praxe.',
  },
  {
    id: 'distribuce',
    group: 'objem',
    term: 'Rozložení intenzit',
    full: 'Histogram zvedů po pětiprocentních pásmech',
    short: 'Jemnější pohled na totéž, co dělí Prilepinova tabulka do čtyř zón.',
    formula: 'pásmo = zaokrouhlení intenzity dolů na násobek pěti\npodíl = zvedy v pásmu ÷ všechny zvedy',
    bands: [
      { range: '70–80 %', label: 'Pásmo, do kterého Sheiko dával většinu práce', tone: 'ok' },
      { range: 'série nad 5 opakování', label: 'U Sheika výjimka — stavěl na kratších sériích a vyšší frekvenci', tone: 'low' },
    ],
    body: 'Prilepinova tabulka rozdělí práci do čtyř hrubých zón. Tenhle histogram je totéž po pěti procentech, takže je z něj vidět tvar rozložení — jestli se práce koncentruje kolem jednoho pásma, nebo je rozprostřená.',
    how: 'Srovnávej tvar, ne absolutní počty. Sheikovy objemy byly psané pro sovětské a ruské profesionály, často farmakologicky podpořené — slepé kopírování počtu zvedů je běžná chyba.',
    source: 'Sheikovy programy a rozbory PowerliftingToWin. Trenérská praxe.',
  },
  {
    id: 'specificnost',
    group: 'objem',
    term: 'Index specifičnosti',
    full: 'Kolik práce jde na samotné soutěžní cviky',
    short: 'V akumulaci nižší, k závodu roste.',
    formula: 'specifičnost = tonáž soutěžních cviků ÷ celková tonáž × 100',
    bands: [
      { range: 'pod 60 %', label: 'Akumulace — hodně variant a doplňků', tone: 'ok' },
      { range: '60–80 %', label: 'Transmutace', tone: 'ok' },
      { range: 'nad 80 %', label: 'Realizace — skoro jen soutěžní cviky v soutěžním provedení', tone: 'ok' },
    ],
    body: 'Bloková periodizace čeká, že specifičnost k závodu poroste. Daleko od závodu se dá stavět kapacita variantami a doplňky; blízko závodu má většina práce vypadat jako to, co se bude dělat na platformě.',
    how: 'Není to hodnotící metrika — nízká specifičnost není chyba, pokud je zrovna akumulace. Chyba je, když se nemění: plochá křivka celou sezónu znamená, že blok nemá fázi.',
    source: 'Odvozeno z principu blokové periodizace (Issurin). Appka to počítá přímo z dat, nejde o publikovaný vzorec.',
  },
  {
    id: 'sfr',
    group: 'unava',
    term: 'Poměr podnětu k únavě',
    full: 'Který cvik vrací nejvíc za nejmíň',
    short: 'Vlastní heuristika appky, ne převzatá metoda.',
    formula: 'podnět = tvrdé série × (průměrná intenzita ÷ 100)\núnava = součet INOL\npoměr = podnět ÷ únava',
    bands: [
      { range: 'vyšší poměr', label: 'Cvik vrací víc adaptace za stejnou cenu', tone: 'ok' },
      { range: 'nižší poměr', label: 'Stejná únava, menší podnět', tone: 'warn' },
    ],
    body: 'V původní podobě je poměr podnětu k únavě subjektivní škála, kterou kouč vyplní podle pocitu. Číselná verze v appce je moje konstrukce a nikdy nebyla proti ničemu ověřená.',
    how: 'Porovnávej cviky jednoho člověka mezi sebou, ne absolutní hodnoty a ne mezi závodníky. Z absolutního čísla se nedá vyvodit nic — nemá měřítko.',
    source: 'Koncept z Renaissance Periodization je čistě subjektivní hodnocení. Číselná podoba je konstrukce této aplikace, ne převzatá věda.',
  },
  {
    id: 'shazovani',
    group: 'zavod',
    term: 'Shazování váhy',
    full: 'Kolik zbývá do limitu a jak riskantní to je',
    short: 'Kalkulačka a hranice rizika. Ne návod, jak shazovat.',
    formula: 'podíl = (tělesná váha − limit) ÷ tělesná váha × 100',
    bands: [
      { range: 'do 2 %', label: 'Nízké riziko — dieta a vyprázdnění střev', tone: 'ok' },
      { range: '2–5 %', label: 'Střední. Uvnitř pásma, které přehledy považují za relativně bezpečné', tone: 'warn' },
      { range: 'nad 5 %', label: 'Vysoké. Mimo doporučené pásmo', tone: 'bad' },
    ],
    body: 'Shazuje 97 % trojbojařů, typicky 4,2 % hmotnosti — na regionálních závodech víc než na mezinárodních. Zhruba 70 % závodníků přitom popisuje psychický dopad jako negativní: únavu, úzkost, podrážděnost. Řízený pokus ukázal, že při zhruba pěti procentech a dostatečné regeneraci se maximální síla udrží.',
    how: 'Appka spočítá rozdíl a řekne, kde jsou hranice. Samotný postup má vést někdo, kdo na to má vzdělání — protokoly na vodní nálož kolující po internetu jsou z velké části bez dobré evidence a nesou reálné riziko hyponatremie. A ověř si čas vážení: IPF váží dvě hodiny předem, jiné federace čtyřiadvacet, a bez toho čísla věta o udržení výkonu neplatí.',
    source: 'Campbell a kol. (2025) pro rozšířenost a typický shoz; řízený pokus PMC12392435 pro dopad na výkon. Pásmo 3–5 % je z přehledových prací. Přesné znění časů vážení v pravidlech ověřené není — koukni do aktuálního rulebooku své federace.',
  },
  {
    id: 'rpe',
    group: 'zaklad',
    term: 'RPE',
    full: 'Rate of Perceived Exertion — míra vnímaného úsilí',
    short: 'Desetibodová škála, na které závodník po sérii řekne, jak těžká byla.',
    bands: [
      { range: '10', label: 'Maximum, nic by už nevyjelo', tone: 'bad' },
      { range: '9', label: 'Zbývalo přesně jedno opakování', tone: 'warn' },
      { range: '8', label: 'Zbývala dvě', tone: 'ok' },
      { range: '7', label: 'Zbývala tři, tyč jede svižně', tone: 'ok' },
      { range: '6 a níž', label: 'Čtyři a víc, technická práce', tone: 'low' },
    ],
    body: 'Procenta z maxima neznají špatně prospanou noc ani stres v práci. RPE ano — je to zpětná vazba z konkrétního dne. Na tom stojí celá autoregulace.',
    how: 'U nového závodníka si prvních pár týdnů ověřuj, jestli jeho RPE 8 opravdu znamená dvě opakování v záloze. Většina lidí zpočátku podhodnocuje — hlásí osmičku tam, kde je devítka.',
    source: 'Škálu do silového tréninku zavedl Mike Tuchscherer (Reactive Training Systems, 2008).',
  },
  {
    id: 'rir',
    group: 'zaklad',
    term: 'RIR',
    full: 'Reps In Reserve — opakování v záloze',
    short: 'Druhá strana téže mince: kolik opakování by ještě šlo udělat.',
    formula: 'RIR = 10 − RPE',
    body: 'RPE 8 znamená RIR 2. Někteří závodníci uvažují líp v opakováních než v úsilí — pak se ptej „kolik bys ještě dal?" místo „jak to bylo těžké?".',
    how: 'Otázka na RIR se pokládá hned po odložení činky, ne po pauze. Po třech minutách si každý myslí, že mohl víc.',
    source: 'Zilinskas a kol.; koncept rozšířil Renaissance Periodization.',
  },
  {
    id: 'rel-intenzita',
    group: 'zaklad',
    term: 'Relativní intenzita',
    full: 'Procenta z denního maxima, ne z maxima na papíře',
    short: 'Kolik procent to bylo z toho, co závodník zvládal *ten den*.',
    formula: 'relativní % = váha ÷ maximum toho dne × 100',
    body: 'Absolutní intenzita je jediné číslo, které většina aplikací umí: 170 kg je pořád 85 % z dvousetkilového maxima, ať je člověk čerstvý nebo rozbitý. Denní maximum se ale mění — po špatně prospané noci může být 185 a stejných 170 kg je najednou 92 %. A přesně proto ta série jede na RPE 9 místo osmičky. Rozdíl mezi absolutní a relativní intenzitou je jméno pro to, čemu se v hovoru říká „špatný den".',
    bands: [
      { range: 'pod −2', label: 'Dobrý den — denní maximum nad papírovým, dá se přitlačit', tone: 'ok' },
      { range: '−2 až +2', label: 'Podle plánu — denní maximum sedí na to, s čím plán počítal', tone: 'ok' },
      { range: '+2 až +5', label: 'Těžší den — jednou se to stane, opakovaně je to signál', tone: 'warn' },
      { range: 'nad +5', label: 'Špatný den — série byly relativně mnohem těžší, než plán čekal', tone: 'bad' },
    ],
    how: 'Jeden špatný den má obvykle příčinu mimo trénink a nic v plánu měnit nemusí. Tři po sobě už znamenají posun formy: buď se hromadí únava, nebo maximum v profilu přestalo platit. Ověř obojí dřív, než přidáš objem. Ve dni, kde se dělal víc než jeden cvik, appka denní maximum v kilech neukazuje — procenta se přes cviky průměrovat dají, kila ne.',
    source: 'Práce s denním maximem je jádro metody RTS (Mike Tuchscherer, Reactive Training Systems). Hranice ±2 a ±5 procentních bodů publikované nejsou — jsou to prahy této aplikace, zvolené tak, aby seděly na běžný rozptyl formy ze dne na den.',
  },
  {
    id: 'vazeny-e1rm',
    group: 'zaklad',
    term: 'Vážený odhad maxima',
    full: 'Maximum dne z několika sérií, vážené podle spolehlivosti',
    short: 'Z jednoho dne se nebere nejlepší série, ale vážený průměr všech.',
    formula: 'maximum = Σ(hodnota ÷ σ²) ÷ Σ(1 ÷ σ²)',
    body: 'Vzít z dne nejlepší sérii je lákavé a systematicky špatně. Maximum z několika zašuměných odhadů není odhad středu, ale extrémní hodnota — roste s počtem sérií. Kdo zapíše osm sérií, dostane vyšší číslo než kdo zapíše dvě, i když oba zvedali totéž. Správně se odhady váží obráceně k jejich rozptylu: trojka na RPE 9 nese mnohem víc informace než desítka na RPE 6, u které se RPE odhaduje nejhůř.',
    bands: [
      { range: 'σ ≈ 0,32', label: 'Těžké série nad 90 % — nahlášené RPE je nejspolehlivější', tone: 'ok' },
      { range: 'σ ≈ 0,92', label: 'Kolem 90 %', tone: 'ok' },
      { range: 'σ ≈ 0,97', label: 'Kolem 75 %', tone: 'warn' },
      { range: 'σ ≈ 1,18', label: 'Kolem 60 % — desítka na šestce nenese skoro žádnou informaci', tone: 'low' },
    ],
    how: 'V sekci Plán vs. realita appka vedle váženého odhadu ukazuje i to, o kolik by nejlepší série nadhodnotila. Když je ten rozdíl velký, znamená to, že se ten den hodně kolísalo — víc než že se něco zlepšilo.',
    source: 'Rozptyl nahlášeného RPE podle relativní intenzity: Zourdos a kol. (2016), JSCR 30(1):267–75 — zkušení dřepaři. Samotné vážení obráceně k rozptylu je standardní statistický postup (inverse-variance weighting), ne konstrukce této aplikace. Spojení obojího do odhadu maxima dne už konstrukce této aplikace je.',
  },
  {
    id: 'varianty',
    group: 'zaklad',
    term: 'Koeficienty variant',
    full: 'Odvozené maximum pro pauzovaný dřep, deficitní tah a spol.',
    short: 'Varianta nemá vlastní testované maximum — odvodí se procentem ze soutěžního cviku.',
    formula: 'maximum varianty = maximum soutěžního cviku × koeficient',
    body: 'Pauzovaný dřep, deficitní tah nebo bench úzkým úchopem tvoří v seriózním bloku většinu práce, ale nikdo je netestuje na jeden pokus. Bez odvozeného maxima spadnou mezi doplňkové cviky a vypadnou z intenzity, INOL, Prilepina i tvrdých sérií — a celá analýza bloku pak počítá jen se soutěžními sériemi, kterých je málo. S koeficientem se počítají správně: pauzovaný dřep na 88 % svého maxima není 88 % soutěžního dřepu.',
    bands: [
      { range: 'Box squat 0,92', label: 'Rack pull 1,15 · tah z bloků 1,07 — zkrácený rozsah, zvedne se víc', tone: 'ok' },
      { range: 'Bench úzkým úchopem 0,92', label: 'Spoto press 0,91 · pin press a Larsen 0,90', tone: 'ok' },
      { range: 'Pauzovaný dřep 0,88', label: 'Pauzovaný tah 0,88 · deficitní tah 0,90', tone: 'ok' },
      { range: 'Přední a tempo dřep 0,82', label: 'Nejdál od soutěžního provedení, největší rozptyl mezi lidmi', tone: 'warn' },
    ],
    how: 'Výchozí čísla ber jako startovní odhad, ne jako pravdu. U konkrétního člověka rozhoduje technika a stavba — kdo má dlouhé stehno, ztratí v pauzovaném dřepu víc než kdo má krátké. V profilu svěřence jde každý koeficient přepsat a appka od té chvíle počítá jeho číslo.',
    source: 'Žádná recenzovaná tabulka těchto koeficientů neexistuje. Jsou to hodnoty z trenérské praxe a mezi zdroji se u některých variant liší i o deset procentních bodů — proto je u každé vidět rozptyl, který se v praxi uvádí, a proto jdou všechny přepsat.',
  },
  {
    id: 'nl',
    group: 'zaklad',
    term: 'NL',
    full: 'Number of Lifts — počet zvedů',
    short: 'Kolikrát se tyč pohnula. Série × opakování.',
    formula: 'NL = série × opakování',
    body: 'Nejstarší měřítko objemu v silovém sportu. Nezajímá ho, jak těžká váha byla — jen kolik opakování proběhlo. Proto se vždy počítá zvlášť pro každé intenzitní pásmo.',
    how: 'V aplikaci se počítá zvlášť NL v hlavních cvicích a NL celkem. Doplňky objem nafouknou, ale o specifické připravenosti neřeknou nic.',
    source: 'Sovětská metodika, používá Prilepinova tabulka.',
  },

  /* ---------------- Objem a intenzita ---------------- */
  {
    id: 'tonaz',
    group: 'objem',
    term: 'Tonáž',
    full: 'Volume load — objemová zátěž',
    short: 'Kolik kilogramů celkem prošlo rukama.',
    formula: 'Tonáž = série × opakování × váha',
    body: 'Jediné číslo, které spojí objem s vahou na ose. 5 × 5 × 100 kg je 2 500 kg. Hodí se na porovnání týdnů mezi sebou, ne na porovnání dvou různých závodníků.',
    how: 'Sleduj směr, ne absolutní hodnotu. Bezpečný přírůstek je do 10 % týdně. Skok o třetinu je varování, i když se závodník cítí dobře.',
    source: 'Standardní ukazatel; taperové studie ho používají jako hlavní proměnnou.',
  },
  {
    id: 'intenzita',
    group: 'objem',
    term: 'Relativní intenzita',
    full: 'Podíl použité váhy na maximu',
    short: 'Jak těžké to bylo vzhledem k tomu, co závodník umí.',
    formula: 'Intenzita = váha ÷ E1RM × 100',
    body: 'Sto kilo na dřepu znamená u každého něco jiného. Relativní intenzita to srovná. Průměrná intenzita bloku se váží počtem opakování, aby jedna těžká jednička nepřebila dvacet lehkých.',
    how: 'Rozvoj síly se odehrává hlavně nad 80 %. Průměr celého bloku pod 65 % je objemová práce, nad 87 % je dlouhodobě neudržitelné.',
    source: 'Doplňkové cviky se do průměru nepočítají — nemají změřené 1RM.',
  },
  {
    id: 'tvrda-serie',
    group: 'objem',
    term: 'Tvrdá série',
    full: 'Hard set',
    short: 'Série dost blízko selhání na to, aby něco změnila.',
    formula: 'RPE ≥ 7, nebo intenzita ≥ 70 % bez zapsaného RPE',
    body: 'Rozcvičovací série se nepočítají. Když se mluví o „patnácti sériích týdně", myslí se patnáct tvrdých sérií — zbytek je příprava na ně.',
    how: 'Pro soutěžní cvik je produktivní pásmo zhruba 10 až 18 tvrdých sérií týdně. Pod 6 se síla drží, ale neroste; nad 25 většina lidí neregeneruje.',
    source: 'Odvozeno z mezníků MEV/MAV/MRV; ty jsou původně na svalovou skupinu, ne na soutěžní cvik.',
  },
  {
    id: 'landmarks',
    group: 'objem',
    term: 'MEV / MAV / MRV',
    full: 'Objemové mezníky',
    short: 'Tři hranice: kde objem začne fungovat, kde funguje nejlíp a kde přestane.',
    bands: [
      { range: 'MV', label: 'Udržovací objem — síla se drží, neroste', tone: 'low' },
      { range: 'MEV', label: 'Minimální účinný objem, kolem 6–8 sérií týdně', tone: 'warn' },
      { range: 'MAV', label: 'Maximální adaptační objem, zhruba 12–18 sérií', tone: 'ok' },
      { range: 'MRV', label: 'Maximální zvládnutelný objem — nad ním se dluh nesplácí', tone: 'bad' },
    ],
    body: 'Mezníky nejsou konstanty. Posouvají se s tréninkovým věkem, spánkem, kaloriemi i s tím, kolik cviků závodník dělá. Blok se obvykle staví tak, že začne u MEV a přes týdny se posouvá k MRV, pak přijde deload.',
    how: 'Čísla ber jako startovní odhad, ne jako pravdu. Skutečné MRV poznáš až podle toho, kdy se výkon přestane zlepšovat při rostoucím objemu.',
    source: 'Renaissance Periodization (Israetel a kol.). Původně na svalovou skupinu za týden.',
  },
  {
    id: 'prilepin',
    group: 'objem',
    term: 'Prilepinova tabulka',
    full: 'Doporučený počet zvedů podle intenzitního pásma',
    short: 'Kolik opakování dává v které zóně smysl.',
    bands: [
      { range: 'pod 70 %', label: '3–6 opakování v sérii · 18–30 zvedů, ideál 24', tone: 'low' },
      { range: '70–79 %', label: '3–6 opakování · 12–24 zvedů, ideál 18', tone: 'ok' },
      { range: '80–89 %', label: '2–4 opakování · 10–20 zvedů, ideál 15', tone: 'warn' },
      { range: '90 % a výš', label: '1–2 opakování · 4–10 zvedů, ideál 7', tone: 'bad' },
    ],
    body: 'A. S. Prilepin prošel tréninkové deníky přes tisíc medailistů a vypsal, kolik zvedů v jaké zóně dávali. Pásma platí na jeden cvik a jednu jednotku, ne na celý týden.',
    how: 'Nad horní hranicí v těžkých zónách klesá kvalita provedení. Pod dolní hranicí se nestihne nic naučit. Tabulka vznikla na vzpírání — v trojboji se dolní pásma běžně překračují a nic se neděje.',
    source: 'A. S. Prilepin, sovětský výzkum vzpírání; do angličtiny přenesl mimo jiné Hristov.',
  },
  {
    id: 'inol',
    group: 'objem',
    term: 'INOL',
    full: 'Intensity + Number Of Lifts',
    short: 'Starší způsob vážení objemu těžkostí. V appce ho nahradily tvrdé série — historie a kontext, proč.',
    formula: 'INOL = opakování ÷ (100 − intenzita v %)',
    body: 'Deset opakování na 70 % dá 10 ÷ 30 = 0,33. Stejných deset opakování na 90 % dá 10 ÷ 10 = 1,00 — třikrát víc. Nápad je dobrý: těžké zvedy stojí víc než lehké. Problém je citlivost na počet opakování v sérii, ne na to, jak blízko selhání série byla — jedna maximální jednička (1 opakování) vyjde skoro vždy jako „lehká", i když je to nejtěžší věc, co ten den kdo udělal.',
    bands: [
      { range: 'pod 0,4', label: 'Jednotka: podnět nestačí na adaptaci', tone: 'low' },
      { range: '0,4 – 1,0', label: 'Jednotka: zvládnutelná dávka', tone: 'ok' },
      { range: '1,0 – 2,0', label: 'Jednotka: náročné, sedí do akumulace', tone: 'warn' },
      { range: 'nad 2,0', label: 'Jednotka: extrémní zatížení', tone: 'bad' },
    ],
    how: 'Appka teď osu objemu počítá přes tvrdé série (heslo o kousek výš) — to je metrika, na které se sjednotila současná trenérská praxe. Jako samostatné číslo se proto INOL nikde nezobrazuje. Nezmizel ale úplně: používá se uvnitř jako váha při počítání denní připravenosti, protože přesně vystihuje, kolik informace která série nese — trojka na devítce váží víc než desítka na šestce. Jako reference se hodí i tehdy, když narazíš na starší plán, který s ním počítá.',
    source: 'Hristo Hristov, „How to Design Strength Training Programs using Prilepin\'s Table".',
  },
  {
    id: 'tezke-expozice',
    group: 'objem',
    term: 'Těžké expozice',
    full: 'Kolikrát ses dotkl 85 / 90 / 95 % z 1RM',
    short: 'Počet samostatných dnů u cviku, kdy série dosáhla dané hranice intenzity nebo víc.',
    formula: 'Expozice na hranici X % = počet dnů u cviku, kdy alespoň jedna série ≥ X % z 1RM',
    bands: [
      { range: '≥ 85 %', label: 'Těžká práce, ale ještě daleko od maxima', tone: 'low' },
      { range: '≥ 90 %', label: 'Skutečně těžké — nervová soustava to pozná', tone: 'warn' },
      { range: '≥ 95 %', label: 'Prakticky maximální — vyhraněné pro vrchol bloku', tone: 'bad' },
      { range: 'více sérií, jeden den', label: 'Počítá se jako jedna expozice, ne víc', tone: 'neutral' },
    ],
    body: 'Bloková periodizace (Akumulace → Transmutace → Realizace) staví na tom, že se specifičnost — práce blízko soutěžní intenzitě — postupně zvyšuje. Počet těžkých expozic je nejjednodušší způsob, jak tenhle nárůst vidět: akumulace by jich měla mít málo nebo žádné, realizace před závodem hodně. Víc sérií nad 90 % ve stejné jednotce se počítá jako jedna expozice — fyziologicky je to pořád jeden těžký den, ne tři.',
    how: 'Appka nepřiřazuje k prahům žádné „bezpečné pásmo" — na rozdíl od Prilepina nebo taperu tu není publikovaný číselný standard. Sleduj trend přes týdny bloku: pokud realizační týden nemá jedinou expozici ≥ 90 %, blok postrádá specificitu; pokud jich má skoro každý den moc týdnů v řadě, riskuješ přetížení stejně jako u tvrdých sérií.',
    source: 'Odvozeno z principu blokové periodizace (Verchoshansky; Issurin) — expozice samy appka počítá přímo z dat, nejde o publikovaný vzorec s vlastními koeficienty.',
  },

  /* ---------------- Únava a zátěž ---------------- */
  {
    id: 'plan-vs-realita',
    group: 'unava',
    term: 'Plán vs. realita',
    full: 'Co bylo napsané proti tomu, co se doopravdy stalo',
    short: 'Nejpřímější signál únavy, jaký z tréninku dostaneš.',
    formula: 'odchylka RPE = skutečné RPE − plánované RPE\nodchylka váhy = skutečná váha − plánovaná váha',
    bands: [
      { range: 'do −0,4', label: 'Lehčí, než plán čekal — dá se přitlačit', tone: 'low' },
      { range: '−0,4 až +0,3', label: 'Jede se podle plánu', tone: 'ok' },
      { range: '+0,3 až +0,7', label: 'Těžší, než plán — sledovat', tone: 'warn' },
      { range: 'nad +0,7', label: 'Výrazně těžší. Hromadí se únava', tone: 'bad' },
    ],
    body: 'Plán a skutečnost jsou dvě různá čísla a appka si je nepřepisuje. Plánovaná váha a RPE zůstávají tak, jak byly napsané; vedle nich se zapisuje, co se doopravdy naložilo, kolik opakování padlo a na jaké RPE to šlo. Teprve tím vzniká dvojice, kterou jde porovnat — kdyby se plán zápisem přemazal, po tréninku by už nikdo nezjistil, že se místo naplánovaných 170 zvedlo 160.',
    how: 'Prázdné pole znamená „šlo to podle plánu" — vyplňovat se musí jen to, co se lišilo. Všechno, co popisuje odvedený trénink (tonáž, intenzita, odhad maxima, únava dne), pak počítá se skutečnými hodnotami tam, kde jsou zapsané, a s plánem tam, kde ještě nejsou. Série, které teprve přijdou, se tím nerozbijí.',
    source: 'Princip autoregulace podle Reactive Training Systems (Tuchscherer). Oddělení plánu a skutečnosti je návrhové rozhodnutí appky, ne metoda z literatury.',
  },
  {
    id: 'hooper',
    group: 'unava',
    term: 'Hooperův index',
    full: 'Kvantifikovaná pohoda — spánek, stres, únava, bolestivost',
    short: 'Čtyři čísla denně, která zachytí i to, co RPE nevidí — život mimo posilovnu.',
    formula: 'index = spánek + stres + únava + bolestivost, každá položka 1–7',
    bands: [
      { range: '4', label: 'Nejlepší možný stav — všechny položky na 1', tone: 'ok' },
      { range: '28', label: 'Nejhorší možný stav — všechny položky na 7', tone: 'bad' },
      { range: 'proti vlastnímu průměru', label: 'Appka nehlídá pevnou hranici, jen odchylku od tebe samotného', tone: 'low' },
    ],
    body: 'RPE měří, jak těžká byla série — ale netuší, jestli za to může trénink, nebo špatně prospaná noc a stres v práci. Hooper a Mackinnon (1995) u plavců ukázali, že součet těchhle čtyř jednoduchých otázek předpověděl 76 % rozptylu fyziologických markerů přetrénování — bez jediného měřáku.',
    how: 'Appka porovnává dnešní součet s klouzavým průměrem posledních dnů, ne s univerzální hranicí — ta pro Hooperův index nikdy nebyla stanovena, validoval se jako nástroj pro sledování jednoho člověka v čase. Odchylka aspoň o 2 body od vlastního průměru je appkou zvolený orientační práh, ne publikované číslo.',
    source: 'Hooper, Mackinnon a kol. (1995), Medicine & Science in Sports & Exercise.',
  },
  {
    id: 'unava-procenta',
    group: 'unava',
    term: 'Únava v %',
    full: 'Fatigue percent podle RTS',
    short: 'O kolik klesl odhad maxima od nejlepší série dne.',
    formula: 'únava % = (nejlepší E1RM dne − poslední E1RM) ÷ nejlepší E1RM × 100',
    bands: [
      { range: 'do 2 %', label: 'Skoro bez únavy — dalo by se přidat', tone: 'low' },
      { range: '2–6 %', label: 'Běžná dávka na pracovní jednotku', tone: 'ok' },
      { range: '6–10 %', label: 'Hodně únavy', tone: 'warn' },
      { range: 'nad 10 %', label: 'Série už jen přidávají únavu, ne kvalitu', tone: 'bad' },
    ],
    body: 'Tuchscherer to postavil obráceně než většina metrik: nesleduje, kolik práce se udělalo, ale jak se během jednotky mění odhad maxima. Když po třech sériích spadne o 5 %, víš přesně, kolik toho z tebe trénink vytáhl.',
    how: 'Počítá se zvlášť pro každý cvik a den — porovnávat dřep s benčem nedává smysl. Potřebuje aspoň dvě zapsané série jednoho cviku se skutečným RPE.',
    source: 'Reactive Training Systems, „Fatigue Percents Revisited".',
  },
  {
    id: 'forma',
    group: 'unava',
    term: 'Kondice, únava a forma',
    full: 'Dvousložkový model odezvy (Banister)',
    short: 'Jedna dávka tréninku nastartuje kondici i únavu naráz. Výkon je jejich rozdíl.',
    formula: 'kondice(t) = kondice(t−1) · e^(−1/τ1) + zátěž(t)\núnava(t)   = únava(t−1)   · e^(−1/τ2) + zátěž(t)\nforma(t)   = k1 · kondice(t) − k2 · únava(t)\n\nτ1 = 42 dnů, τ2 = 7 dnů, k1 = 1, k2 = 2',
    bands: [
      { range: 'Nahoře', label: 'Forma v horní pětině vlastní historie — tady se testuje a závodí', tone: 'ok' },
      { range: 'Obvyklý stav', label: 'Kondice a únava v rovnováze, na kterou je závodník zvyklý', tone: 'ok' },
      { range: 'Zahrabaný', label: 'Únava přerůstá kondici — v akumulaci správně, před testem ne', tone: 'warn' },
      { range: 'Hluboko', label: 'Forma na dně vlastní historie', tone: 'bad' },
    ],
    body: 'Model vysvětlí věc, která se jinak těžko obhajuje: proč se závodník po odlehčovacím týdnu cítí silnější, i když v něm nic těžkého nezvedl. Kondice roste pomalu a odeznívá pomalu, únava roste rychle a mizí rychle. Když se přestane přidávat práce, únava spadne dřív, než stihne spadnout kondice — a jejich rozdíl, tedy to, co se ukáže na platformě, vyskočí nahoru. Tomu se říká okno formy a taper není nic jiného než snaha ho trefit na den závodu.',
    how: 'Čti tvar křivky, ne číslo. Před závodem chceš vidět, jak se oranžová (únava) propadá pod modrou (kondice) a zelená (forma) šplhá k horní části vlastního rozpětí. Uprostřed objemového bloku má být forma dole — to není chyba, to je práce, ze které se teprve bude regenerovat.',
    source: 'Banister a kol. (1975), Calvert a kol. (1976). POZOR: časové konstanty 42 a 7 dnů a poměr k2/k1 = 2 pocházejí z vytrvalostních sportů; individuálně nafitované hodnoty pro silový trénink publikované nejsou. Appka proto počítá v bezrozměrných jednotkách, čte je jen proti vlastní historii závodníka a nikdy nepředpovídá kilogramy.',
  },
  {
    id: 'denni-pripravenost',
    group: 'unava',
    term: 'Denní připravenost',
    full: 'Odchylka RPE od očekávání, z-skórovaná',
    short: 'Jestli byl dnešek těžší nebo lehčí, než měl podle plánu být.',
    formula: 'odchylka série = skutečné RPE − očekávané RPE(intenzita, opakování)\ndenní skóre = vážený průměr odchylek, váha = INOL\nz = (denní skóre − průměr 28 dnů) ÷ směrodatná odchylka',
    bands: [
      { range: 'z ≤ −1', label: 'Šlo to líp, než plán čekal — odpočatý, nebo se plán podceňuje', tone: 'ok' },
      { range: '−1 až +1', label: 'Trénink sedí na to, jak byl napsaný', tone: 'ok' },
      { range: 'z ≥ +1', label: 'Den byl náročnější, než měl být. Jednou šum, třikrát signál', tone: 'warn' },
      { range: 'z ≥ +1,5', label: 'Výrazně hůř, než u tohohle závodníka bývá zvykem', tone: 'bad' },
    ],
    body: 'Nejlepší odhad připravenosti, který jde z deníku vytáhnout bez jediného přístroje navíc. U každé série se z relativní intenzity a počtu opakování odvodí, na jaké RPE měla vyjít; rozdíl proti nahlášenému RPE je odchylka. Série se váží podle INOL, protože přesnost odhadu RPE prudce klesá s počtem opakování — Zourdos a kol. naměřili u zkušených dřepařů směrodatnou odchylku nahlášeného RPE 0,32 bodu při 100 % 1RM, ale 1,18 při 60 %. Trojka na RPE 9 tedy nese informaci, desítka na RPE 6 skoro žádnou.',
    how: 'Čte se jako z-skóre proti vlastnímu klouzavému oknu, ne proti pevné hranici — někdo hlásí RPE systematicky výš než jiný a absolutní číslo by se mezi závodníky nedalo porovnat. Je to per-jednotka a normalizovaná obdoba posunu RPE, který appka počítá po týdnech: ten ukáže trend bloku, tenhle jeden konkrétní den.',
    source: 'Konstrukce nad publikovaným základem: Helms a kol. (2017) pro vztah % 1RM a RPE (r = 0,88–0,91), Zourdos a kol. (2016) pro přesnost nahlášeného RPE podle intenzity. Samotné z-skórování je běžná statistika, ne sportovní věda.',
  },
  {
    id: 'mrv-signal',
    group: 'unava',
    term: 'Strop regenerace',
    full: 'Tři známky dosaženého MRV',
    short: 'Kdy objem přerostl schopnost regenerace — a je čas odlehčit.',
    formula: '1) výkon nejde nahoru při stejném nebo větším objemu\n2) stejný plán jede o 0,5 RPE dráž než minule\n3) Hooperův index o 15 % horší než vlastní průměr\n\ndvě ze tří naráz = strop',
    bands: [
      { range: '0 známek', label: 'Objem je v mezích regenerace', tone: 'ok' },
      { range: '1 známka', label: 'Sama o sobě bývá šum — sledovat, jestli přibude druhá', tone: 'warn' },
      { range: '2 a víc', label: 'Další série nepřidá adaptaci, jen únavu. Odlehčit', tone: 'bad' },
    ],
    body: 'Objemové mezníky MEV, MAV a MRV se běžně uvádějí jako konkrétní počty sérií, jenže ta čísla nejsou nikde empiricky změřená — jsou to trenérské odhady prezentované s větší jistotou, než jakou data unesou. Appka proto žádnou hranici v sériích netvrdí a místo toho hlídá důsledky. Žádná známka sama o sobě nestačí: výkon může stát kvůli jednomu lehkému týdnu, RPE může vyskočit po jedné špatné jednotce a pohodu zkazí práce i chřipka. Dvě nezávislé naráz už ale ukazují stejným směrem.',
    how: 'Když sedí dvě ze tří, přidávání objemu se přestalo vyplácet. Týden odlehčení — objem dolů zhruba o polovinu, intenzitu držet — vrátí víc než další série. Pozor na první známku: stagnace výkonu se počítá jen tehdy, když objem neklesl. Po deloadu výkon stojí z jiného důvodu a appka to nezaměňuje.',
    source: 'Israetel, Hoffmann, Smith — Scientific Principles of Strength Training (RP, 2015) pro samotné mezníky (trenérská praxe, ne recenzovaný důkaz). Podklad k dávce a odezvě: Pelland, Schoenfeld a kol., Sports Medicine (2025), doi 10.1007/s40279-025-02344-w — 67 studií, 2058 účastníků; u síly jsou klesající výnosy z objemu výrazně strmější než u hypertrofie. Samotná kombinace tří známek je konstrukce appky nad hodnotami, které už počítá.',
  },
  {
    id: 'proc-ne-acwr',
    group: 'unava',
    term: 'Co v appce záměrně není',
    full: 'ACWR, monotonie, strain',
    short: 'Metriky, které appka počítat umí, ale neukazuje — a proč.',
    bands: [
      { range: 'ACWR', label: 'Poměr akutní a chronické zátěže', tone: 'bad' },
      { range: 'Monotonie', label: 'Jednotvárnost týdne', tone: 'warn' },
      { range: 'Strain', label: 'Zátěž × monotonie', tone: 'warn' },
    ],
    body: 'ACWR se roky bral jako standard prevence zranění. Impellizzeri a kolegové (2020) ale ukázali, že má zabudovanou statistickou vadu: akutní zátěž je součástí chronické, takže vztah mezi nimi vzniká sám od sebe i u náhodných dat. Autoři shrnují, že pro řízení tréninku není důkaz. Monotonie a strain pocházejí z vytrvalostních a týmových sportů, kde se trénuje šestkrát týdně podobně — v silovém tréninku se záměrně střídají těžké a lehké dny, takže vysoká monotonie tam nic špatného neznamená.',
    how: 'Místo nich appka ukazuje posun RPE a odhad maxima ze skutečných sérií. Obojí měří přímo to, co tě zajímá — jestli závodníka trénink dobíjí, nebo vysává.',
    source: 'Impellizzeri a kol. (2020), Sports Medicine; Foster (1998) pro monotonii.',
  },
  {
    id: 'charakter-tydne',
    group: 'objem',
    term: 'Charakter týdne',
    full: 'Objem a intenzita jsou dvě různé věci',
    short: 'Proč týden s maximálními singly může mít málo tvrdých sérií a přesto být ten nejtěžší.',
    formula: 'Objem = tvrdé série na cvik a týden\nŠpička = nejtěžší série týdne v % z 1RM',
    bands: [
      { range: 'Deload', label: 'Žádná tvrdá série, nízká intenzita — skutečné odlehčení', tone: 'low' },
      { range: 'Objemová práce', label: '12+ tvrdých sérií, střední váhy — únava sedí ve svalech', tone: 'warn' },
      { range: 'Ostré, málo objemu', label: 'Pod 3 tvrdé série, špička nad 90 % — vrcholení, nervová soustava naplno', tone: 'warn' },
      { range: 'Velmi náročné', label: 'Vysoký objem i maximální váhy naráz', tone: 'bad' },
    ],
    body: 'Objem se v appce měří tvrdými sériemi na cvik a týden (RPE 7 a výš), ne tonáží. Tonáž by odměnila nekonečné lehké série stejně jako pár těžkých — spočítá kila, ne blízkost selhání.',
    how: 'Čti tvrdé série a Špičku vedle sebe. Týden s 1×1 na 92 % a jedním back-off párem má sotva 3 tvrdé série na cvik — objemově skoro nic, ale je to nejostřejší týden v bloku. Regenerace po něm nepotřebuje jídlo a čas na svaly, ale spánek a klid na nervovou soustavu. Málo sérií + vysoká špička = vrcholení, ne lehký týden.',
    source: 'Tvrdé série jako objemová metrika: Helms, Schoenfeld. Rozlišení objem/intenzita je běžná trenérská praxe.',
  },
  {
    id: 'acwr',
    group: 'unava',
    term: 'ACWR',
    full: 'Acute:Chronic Workload Ratio — poměr akutní a chronické zátěže',
    short: 'Kolikrát je poslední týden těžší než to, na co je závodník zvyklý.',
    formula: 'ACWR = zátěž za 7 dní ÷ průměrný týden z posledních 28 dní',
    bands: [
      { range: 'pod 0,8', label: 'Zátěž klesá — buď taper, nebo ztrácíš formu', tone: 'low' },
      { range: '0,8 – 1,3', label: 'Bezpečné pásmo', tone: 'ok' },
      { range: '1,3 – 1,5', label: 'Zvýšené riziko', tone: 'warn' },
      { range: 'nad 1,5', label: 'Skok v zátěži', tone: 'bad' },
    ],
    body: 'Myšlenka je jednoduchá: tělo snese hodně, pokud si na to postupně zvyklo. Problém nedělá vysoká zátěž, ale rychlá změna zátěže.',
    how: 'Ber to jako budík, ne jako diagnózu. Impellizzeri a kol. (2020) ukázali, že ACWR má vážné metodické slabiny — akutní zátěž je součástí chronické, takže korelace vzniká sama od sebe. Když čtyři týdny stojíš, jediná normální jednotka vystřelí poměr nad 2 a nic to neznamená.',
    source: 'Gabbett (2016); kritika Impellizzeri a kol. (2020). V appce se nikde nezobrazuje — proč, je v hesle „Co v appce záměrně není".',
  },
  {
    id: 'ewma',
    group: 'unava',
    term: 'EWMA',
    full: 'Exponenciálně vážený klouzavý průměr',
    short: 'Přesnější způsob, jak počítat ACWR.',
    formula: 'zátěž_dnes × λ + předchozí × (1 − λ),   λ = 2 ÷ (N + 1)',
    body: 'Prostý klouzavý průměr dává dni před měsícem stejnou váhu jako včerejšku a den, který vypadne z okna, zmizí naráz. EWMA váhu plynule snižuje — přesně jako odeznívá únava.',
    how: 'Aplikace ukazuje obě čísla. Když se výrazně rozcházejí, spolehni se na EWMA — bývá realističtější, hlavně po pauze nebo po nemoci.',
    source: 'Williams a kol. (2017), British Journal of Sports Medicine. V appce se nikde nezobrazuje — proč, je v hesle „Co v appce záměrně není".',
  },
  {
    id: 'srpe',
    group: 'unava',
    term: 'sRPE',
    full: 'Session RPE — zátěž tréninkové jednotky',
    short: 'Jak těžký byl celý trénink, ne jedna série.',
    formula: 'Zátěž jednotky = sRPE × počet sérií',
    body: 'Foster původně násobil sRPE délkou tréninku v minutách. U silového tréninku se místo minut dosazují série — délka jednotky totiž závisí hlavně na tom, jak dlouhé si kdo dává pauzy.',
    how: 'Nejlíp funguje, když závodník nahlásí jedno číslo zhruba půl hodiny po tréninku. Aplikace ho zatím dopočítává z RPE jednotlivých položek — je to odhad, ne měření.',
    source: 'Foster a kol. (2001); úprava pro silový trénink McGuigan.',
  },
  {
    id: 'monotonie',
    group: 'unava',
    term: 'Monotonie a strain',
    full: 'Jednotvárnost tréninku a celkové zatížení',
    short: 'Jestli má týden špičky a údolí, nebo je pořád stejně těžký.',
    formula: 'Monotonie = průměr denní zátěže ÷ směrodatná odchylka\nStrain = týdenní zátěž × monotonie',
    bands: [
      { range: 'pod 1,5', label: 'Pestrý týden, těžké i lehké dny', tone: 'ok' },
      { range: '1,5 – 2,0', label: 'Sledovat', tone: 'warn' },
      { range: 'nad 2,0', label: 'Jednotvárné — spolu s vysokou zátěží rizikové', tone: 'bad' },
    ],
    body: 'Dny volna se počítají jako nula a právě ony monotonii snižují. Tři stejně těžké tréninky a čtyři dny volna dají nižší monotonii než šest vlažných jednotek za sebou.',
    how: 'Když monotonie roste a zároveň roste strain, závodník jede pořád na stejné obrátky. Vlož lehký den — ne další volno, ale reálně lehčí trénink.',
    source: 'Foster (1998), „Monitoring training in athletes with reference to overtraining syndrome". V appce se nikde nezobrazuje — proč, je v hesle „Co v appce záměrně není".',
  },

  /* ---------------- Plánování ---------------- */
  {
    id: 'doporuceni',
    group: 'planovani',
    term: 'Doporučení',
    full: 'Co appka vidí — a proč nic nepřepisuje',
    short: 'Signály z ostatních obrazovek seřazené podle naléhavosti, s vyznačenou silou důvodu.',
    formula: 'naléhavost 1 = jednej teď · 2 = tenhle týden · 3 = dobré vědět\nsíla důvodu: studie / praxe / appka',
    bands: [
      { range: 'studie', label: 'Opřeno o recenzovaný zdroj', tone: 'ok' },
      { range: 'praxe', label: 'Trenérská konvence nebo federační norma, ne výzkum', tone: 'low' },
      { range: 'appka', label: 'Konstrukce této aplikace — užitečná, nikde neověřená', tone: 'warn' },
    ],
    body: 'Appka umí spočítat, že příští týden vychází o pár procent jinak. Neví ale, že závodník minulý týden stěhoval, že ho bolí rameno nebo že za měsíc jede na dovolenou. Automatický přepis plánu by tyhle informace přebil čísly, která je neznají — proto obrazovka jen řekne, co se stalo, co s tím, a jak silný je pro to důvod. Zápis zůstává na koučovi.',
    how: 'Sílu důvodu čti jako váhu, ne jako pravdivost. Doporučení označené „appka" nemusí být horší rada než to označené „studie" — jen za ním nestojí nic než logika téhle aplikace, takže když ti odporuje vlastní zkušenost, má vyhrát zkušenost. U „studie" je ta laťka opačně.',
    source: 'Sestavování samo je konstrukce této aplikace. Jednotlivá doporučení nesou sílu důvodu toho pojmu, ze kterého vycházejí — ta je u každého vidět.',
  },
  {
    id: 'frekvence',
    group: 'planovani',
    term: 'Frekvence a rozestupy',
    full: 'Kolikrát týdně cvik a jak daleko od sebe těžké jednotky',
    short: 'Rozložení do dnů, ze kterého jsou vidět chyby, co v tabulce zaniknou.',
    formula: 'frekvence = samostatné dny s cvikem ÷ počet týdnů\nrozestup = dny mezi po sobě jdoucími jednotkami nad 85 % maxima',
    bands: [
      { range: 'pod 1×/týden', label: 'Technika se na takové frekvenci drží těžko', tone: 'warn' },
      { range: '2–3×/týden', label: 'Pásmo, na kterém stojí většina programů, které něco dokázaly', tone: 'ok' },
      { range: 'nad 3×/týden', label: 'Jde to, ale objem v jednotce musí odpovídajícím způsobem klesnout', tone: 'warn' },
      { range: 'rozestup 1 den', label: 'Dvě těžké jednotky téhož cviku po sobě — skoro vždy plánovací chyba', tone: 'bad' },
    ],
    body: 'Některé chyby jsou vidět až z rozložení do dnů, ne z týdenních součtů: dvě těžké jednotky téhož cviku den po dni, tři dny volna uprostřed bloku, plný objem hned po závodě. Dva zápisy stejného cviku v jeden den jsou přitom jedna jednotka, ne dvě — frekvence počítá dny, ne řádky.',
    how: 'Když appka najde jednodenní rozestup mezi těžkými jednotkami, přetáhni jednu z nich v kalendáři na jiný den. U frekvence platí, že se hýbe spolu s objemem v jednotce: víc jednotek týdně znamená míň práce v každé z nich, ne totéž víckrát.',
    source: 'Pásmo 2–3 jednotky týdně je popis současné praxe, ne změřená optimální hodnota. U rozestupů appka žádnou hranici netvrdí, protože publikovaná neexistuje — jen ukazuje skutečné mezery.',
  },
  {
    id: 'blok',
    group: 'planovani',
    term: 'Bloková periodizace',
    full: 'Akumulace → transmutace → realizace',
    short: 'Tři fáze, ve kterých objem klesá a intenzita roste.',
    bands: [
      { range: 'Akumulace', label: 'Vysoký objem, střední intenzita — staví se základ', tone: 'low' },
      { range: 'Transmutace', label: 'Objem dolů, intenzita nahoru, cviky specifičtější', tone: 'warn' },
      { range: 'Realizace', label: 'Nízký objem, nejvyšší intenzita — vrcholí se', tone: 'bad' },
    ],
    body: 'Každý blok rozvíjí jednu vlastnost pořádně místo tří polovičatě. Klasické Sheikovy programy fungují stejně: #30 je akumulace, #31 transmutace, #32 vrcholení.',
    how: 'Blok má mít 3 až 6 týdnů a končit deloadem. Když po bloku nepřijde odlehčení, další blok začínáš s dluhem.',
    source: 'Verchoshansky; v trojboji rozšířeno přes Sheika a Juggernaut Training Systems.',
  },
  {
    id: 'deload',
    group: 'planovani',
    term: 'Deload',
    full: 'Odlehčovací týden',
    short: 'Plánované snížení zátěže, aby se únava stihla vyplavit.',
    body: 'Sníží se objem, intenzita se drží nebo mírně klesne. Není to týden volna — technika se cvičí dál, jen se z ní neodchází zničený.',
    how: 'Typicky se sníží objem o 40 až 50 % a nechá se stejná nebo mírně nižší váha. Když se závodník po deloadu necítí líp, byl deload buď pozdě, nebo moc krátký.',
    source: 'Standardní praxe blokové periodizace.',
  },
  {
    id: 'taper',
    group: 'planovani',
    term: 'Taper',
    full: 'Vrcholení na závod',
    short: 'Poslední fáze před závodem — únava dolů, forma nahoru.',
    bands: [
      { range: 'Délka', label: 'Nejčastěji 7 až 10 dní, systematické přehledy ≤ 2 týdny', tone: 'ok' },
      { range: 'Objem', label: 'Snížit objemovou zátěž o 41 až 50 %', tone: 'ok' },
      { range: 'Intenzita', label: 'Držet nebo mírně zvýšit — od těžkých vah se neodchází', tone: 'warn' },
    ],
    body: 'Kondice se ztrácí pomalu, únava rychle. Taper stojí na tom rozdílu: ubere se objem, intenzita zůstane, únava odejde dřív než forma.',
    how: 'Nejtěžší dřep a bench dej 7 až 8 dní před závodem, mrtvý tah asi 11 dní — regeneruje se z něj nejdéle. Poslední týden už jen otvíráky a technika.',
    source: 'Grgic a Mikulic (2020), systematický přehled; průzkum mezi 364 severoamerickými závodníky.',
  },
  {
    id: 'autoregulace',
    group: 'planovani',
    term: 'Autoregulace',
    full: 'Řízení zátěže podle denní formy',
    short: 'Váha se neurčuje předem, ale podle toho, jak to jde.',
    body: 'Místo „dřep 4 × 5 na 170 kg" se předepíše „dřep 4 × 5 na RPE 8". Ve špatný den to vyjde na 160, v dobrý na 180 — podnět zůstane stejný.',
    how: 'Nejlíp funguje u zkušených závodníků, kteří umí odhadnout RPE. Začátečníkovi dej pevná procenta a RPE ho zatím jen nauč zapisovat.',
    source: 'Reactive Training Systems (Tuchscherer); příbuzný přístup APRE.',
  },
  {
    id: 'makrocyklus',
    group: 'planovani',
    term: 'Makrocyklus',
    full: 'Sezóna — víc mezocyklů v čase',
    short: 'Nejvyšší úroveň periodizace: řetězec bloků směřujících k jednomu nebo víc závodům.',
    bands: [
      { range: 'Mikrocyklus', label: 'Týden — appka: Charakter týdne', tone: 'low' },
      { range: 'Mezocyklus', label: 'Blok, 3–6 týdnů — appka: Analýza bloku', tone: 'ok' },
      { range: 'Makrocyklus', label: '6–12 měsíců, víc bloků — appka: Makrocyklus', tone: 'warn' },
    ],
    body: 'Blok sám o sobě neřekne, jestli sezóna vůbec sleduje smysluplný tvar. Makrocyklus je pohled napříč víc bloky: jestli objem a intenzita mezi nimi skutečně vlní (akumulace → transmutace → realizace), jak často a jak pravidelně přichází odlehčení, a jak si závodník vede zápas od zápasu — ne jen blok od bloku.',
    how: 'Blokovou periodizaci lze v sezóně opakovat vícekrát, pokud závodník soutěží víckrát ročně — tradiční model počítá s 1–2 vrcholy za sezónu a 12–16týdenní přípravou, pokročilejší závodníci s víc soutěžemi obvykle jedou jen sílu a vrcholení mezi nimi, bez plné akumulace pokaždé.',
    source: 'Issurin (blokové periodizace); Renaissance Periodization (Israetel) — makrocyklus jako 6–12měsíční rámec.',
  },
  {
    id: 'apre',
    group: 'planovani',
    term: 'APRE',
    full: 'Autoregulatory Progressive Resistance Exercise',
    short: 'Autoregulace podle počtu opakování na testovací sérii, ne podle pocitu.',
    formula: 'Série 1: 50 % ze 6RM × 10 op. → Série 2: 75 % × 6 op. → Série 3: 100 % × AMRAP',
    bands: [
      { range: '0–2 op.', label: 'Série 4 i příští start: −10 %', tone: 'bad' },
      { range: '3–4 op.', label: 'Série 4 i příští start: −5 %', tone: 'warn' },
      { range: '5–7 op.', label: 'Beze změny', tone: 'ok' },
      { range: '8–12 op.', label: 'Série 4 i příští start: +5 %', tone: 'ok' },
      { range: '13 a víc op.', label: 'Série 4 i příští start: +10 %', tone: 'low' },
    ],
    body: 'Kde RTS RPE stojí na subjektivním pocitu (jak těžké to bylo), APRE stojí na tvrdém čísle: kolik opakování reálně vyšlo na sérii, která jde do momentu, kdy by další nešlo. Appka pásma bere jako procenta ze 6RM, ne jako pevná kila — originál z roku 2010 měřil v librách na konkrétních strojích (bench, leg press, hang clean), takže fixní přírůstky by na dřepu nebo v kilogramech neseděly.',
    how: 'Vhodné pro závodníka, kterému RPE dlouho nesedí nebo si ho plete s únavou. Appka po uložení pamatuje 6RM na příště — nemusíš ho každou jednotku znovu odhadovat.',
    source: 'Mann, Thyfault, Ivey, Sayers (2010), Journal of Strength and Conditioning Research.',
  },

  /* ---------------- Závod ---------------- */
  {
    id: 'pokusy',
    group: 'zavod',
    term: 'Výběr pokusů',
    full: 'Otvírák, druhý a třetí pokus',
    short: 'Tři pokusy, tři různé úkoly.',
    bands: [
      { range: '1. pokus', label: '88–92 % maxima — v tréninku by šel na trojku', tone: 'ok' },
      { range: '2. pokus', label: '94–97 % — zjišťuje se, na co je dnes forma', tone: 'warn' },
      { range: '3. pokus', label: '100–103 % — jde se pro rekord', tone: 'bad' },
    ],
    body: 'Rozbor mistrovství světa IPF v klasickém trojboji 2012–2019: závodníci, kteří zvládli třetí pokus, otevírali v průměru na 91 % té váhy a druhý brali na 96 %.',
    how: 'Otvírák je pojistka, ne prohlášení. Po neplatném pokusu se váha nikdy nezvyšuje — buď se opakuje, nebo se ubere 2,5 kg. Skoky bývají 5 až 7,5 % u dřepu a tahu, 3 až 5 % u benče.',
    source: 'Rozbor výsledků mistrovství světa IPF 2012–2019.',
  },
  {
    id: 'uspesnost-pokusu',
    group: 'zavod',
    term: 'Úspěšnost pokusů',
    full: 'Kolik z devíti pokusů sedlo',
    short: 'Metrika, kterou špičkoví koučové sledují napříč víc zápasy, ne jen v rámci jednoho.',
    formula: 'úspěšnost = povedené pokusy ÷ platné pokusy × 100',
    bands: [
      { range: '~93 % (8,46 z 9)', label: 'Průměr vítězů na MS IPF', tone: 'ok' },
      { range: '~74 % (6,66 z 9)', label: 'Průměr celého startovního pole', tone: 'warn' },
    ],
    body: 'Rozbor mistrovství světa IPF v klasickém trojboji ukázal jasný rozdíl mezi vítězi a zbytkem pole — ne v tom, jak těžké váhy zvedali, ale v tom, jak spolehlivě zvládali pokusy, které si vybrali. Jeden zápas málo řekne — je to metrika, která má smysl až v historii víc zápasů za sebou.',
    how: 'Appka ji počítá v Makrocyklu ze zapsaných zápasů. Klesající úspěšnost napříč zápasy i při rostoucím součtu je signál, že se s attempt selection přestřeluje — ne že závodník slábne.',
    source: 'Rozbor 2016 IPF World Classic Powerlifting Championships (Stronger by Science, rozhovor s Mattem Garym).',
  },
  {
    id: 'dots',
    group: 'zavod',
    term: 'DOTS',
    full: 'Dynamic Objective Team Scoring',
    short: 'Přepočet součtu na body napříč váhovými kategoriemi.',
    formula: 'DOTS = součet × 500 ÷ (a + b·bw + c·bw² + d·bw³ + e·bw⁴)',
    body: 'Polynom čtvrtého stupně z tělesné váhy. Vznikl v Německu jako spravedlivější náhrada Wilkse na krajních vahách. Nepatří žádné federaci, používá se hlavně neoficiálně a v online žebříčcích.',
    how: 'Tělesná váha se ořezává na 40 až 210 kg u mužů a 40 až 150 kg u žen — mimo ten rozsah polynom utíká.',
    source: 'Koeficienty ověřené proti referenční implementaci OpenPowerlifting.',
  },
  {
    id: 'ipfgl',
    group: 'zavod',
    term: 'IPF GL Points',
    full: 'IPF GoodLift Points',
    short: 'Oficiální bodování Mezinárodní federace silového trojboje.',
    formula: 'GL = součet × 100 ÷ (A − B · e^(−C · bw))',
    body: 'Platí od 1. května 2020, nahradilo starší IPF formuli z roku 2018 i Wilkse. Každá kombinace pohlaví, vybavení a disciplíny má vlastní tři koeficienty odvozené regresí z výsledků světové špičky.',
    how: 'Tohle je číslo, podle kterého se dělá pořadí na mistrovstvích. Když závodník řeší „kolik mám bodů", myslí většinou tohle.',
    source: 'IPF, tabulka koeficientů z května 2020; ověřeno proti OpenPowerlifting.',
  },
  {
    id: 'wilks',
    group: 'zavod',
    term: 'Wilks',
    full: 'Wilksův koeficient',
    short: 'Původní přepočet z roku 1994. Historie, ne současnost.',
    formula: 'Wilks = součet × 500 ÷ (a + bx + cx² + dx³ + ex⁴ + fx⁵)',
    body: 'Dlouho standard, dnes většinou nahrazený. Kritizovaný za to, že znevýhodňoval velmi lehké a velmi těžké závodníky. V aplikaci zůstává kvůli porovnání se staršími výsledky.',
    how: 'Když někdo porovnává výkon s výsledkem z roku 2015, potřebuješ Wilkse. Na nový cíl použij IPF GL nebo DOTS.',
    source: 'Robert Wilks (1994); meze tělesné váhy podle OpenPowerlifting.',
  },
  {
    id: 'vbt',
    group: 'unava',
    term: 'MVT / VBT',
    full: 'Rychlost tyče jako objektivní náhrada RPE',
    short: 'Jak rychle jede tyč při dané intenzitě, kdy sérii ukončit a jak z toho odhadnout maximum.',
    formula: 'odhad 1RM = sklon · MVT + průsečík\n(sklon a průsečík z regrese váhy na rychlosti přes 3–6 sérií)\n\npokles rychlosti = (nejrychlejší − poslední) ÷ nejrychlejší × 100',
    bands: [
      { range: 'pokles do 10 %', label: 'Málo únavy — podnět na adaptaci je slabý', tone: 'low' },
      { range: '10–25 %', label: 'Pásmo, ve kterém síla roste nejefektivněji', tone: 'ok' },
      { range: '25–40 %', label: 'Nabírá se objem, za cenu vyšší únavy', tone: 'warn' },
      { range: 'nad 40 %', label: 'Nic navíc se nezíská, jen se hromadí únava', tone: 'bad' },
    ],
    body: 'Rychlost při dané váze klesá s únavou dřív, než se propadne počet opakování — proto se používá jako objektivní doplněk RPE. Appka rychlost neměří, musí se zadat z měřáku; má ale i obdobu, která funguje bez přístroje: propad opakování o víc než pětinu proti první sérii nebo skok RPE o dva body odpovídá zhruba dvaceti až pětadvaceti procentům poklesu rychlosti. Tuhle obdobu si appka počítá sama z deníku.',
    how: 'Nejlíp podložená část celého VBT je práh poklesu v sérii, ne odhad maxima. Když jde o sílu, drž pokles do 25 % — vydřená série do selhání je pro rozvoj síly horší volba než ukončit ji včas. U mrtvého tahu odhad maxima z profilu vůbec nepoužívej: appka ho tam schválně neukáže.',
    source: 'Tabulka rychlostí: „Bar Load-Velocity Profile of Full Squat and Bench Press" (PMC9180020) — POZOR, Smithův stroj a mladí rekreačně trénovaní, na volnou osu se nepřenáší jedna k jedné a mezi jedinci kolísá o 11–25 %. Rychlost při maximu u elitních trojbojařů na volné ose: Helms a kol. (2017), JSCR 31(2):292–7, n = 15. Prahy poklesu: Jukic a kol. (2023), Sports Medicine, doi 10.1007/s40279-022-01754-4. Mrtvý tah: PMC5968962 — všechny varianty prahu podhodnotily maximum o 9–15 %, autoři metodu pro tenhle cvik odmítají. Polynomiální rovnice González-Badillo / Sánchez-Medina appka nepočítá: koeficienty se nepodařilo ověřit z původního zdroje. Převod na propad opakování a skok RPE je pravidlo z trenérské praxe, ne změřená ekvivalence.',
  },
];
